# Generated by Django 5.0.3 on 2024-04-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musker", "0003_tweet"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
